apiVersion: skaffold/v2beta8
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
    - image: api
      context: api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .